adminer:
  image: grigiu/sipp

  privileged: true

  ports:
  - "5060:5060"
  - "5070:5070"

  restart: always

### Replace enviroment variable with own configuration
  environment:
  - TERM=vt220      
